name 'cookbook-sample'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook-sample'
long_description 'Installs/Configures cookbook-sample'
version '0.1.0'
